graph:graph.o Graph.o Cube.o Cylinder.o Centrum.o
	g++ graph.o Graph.o Cube.o Cylinder.o Centrum.o -o graph -Wall
graph:graph.cpp
Graph:Graph.h Graph.cpp
Cube:Cube.h Cube.cpp
Cylinder:Cylinder.h Cylinder.cpp
Centrum:Centrum.h Centrum.cpp

clean:
	rm -f graph graph.o Graph.o Cube.o Cylinder.o Centrum.o