graph:graph.o Graph.o Cube.o Cylinder.o Centrum.o
	g++ graph.o Graph.o Cube.o Cylinder.o Centrum.o -o graph
graph:graph.cpp
Graph:Graph.h
Cube:Cube.h
Cylinder:Cylinder.h
Centrum:Centrum.h

clean:
	rm -f graph graph.o Graph.o Cube.o Cylinder.o Centrum.o